#ifndef REPLIES_HPP
# define REPLIES_HPP

# define RPL_WELCOME "001 :Bienvenue sur IRCrash :)"
# define RPL_YOURHOST "002 :Ce nom de domaine a ete base sur des faits reels"
# define RPL_CREATED "003 "
# define RPL_MYINFO "004 "
# define RPL_PING "PING"
# define RPL_UMODEIS "221 "
# define RPL_LISTSTART "321 "
# define RPL_LIST "322 "
# define RPL_LISTEND "323 "
# define RPL_CHANNELMODEIS "324 "
# define RPL_WHOREPLY "352 "
# define RPL_NOTOPIC "331 "
# define RPL_TOPIC "332 "
# define RPL_TOPICWHOTIME "333 "
# define RPL_NAMREPLY "353 "
# define RPL_ENDOFNAMES "366 "
# define RPL_YOUREOPER "381 :You are now an IRC operator"

# define ERR_NOSUCHNICK "401 :"
# define ERR_NOSUCHCHANNEL "403 "
# define ERR_CANNOTSENDTOCHAN "404 "
# define ERR_NOORIGIN "409 "
# define ERR_NOTEXTTOSEND "412 "
# define ERR_UNKNOWNCOMMAND "421 :"
# define ERR_NONICKNAMEGIVEN "431 :No nickname given"
# define ERR_ERRONEUSNICKNAME "432 :Erroneous nickname"
# define ERR_NICKNAMEINUSE "433 :Nick in use"
# define ERR_USERNOTINCHANNEL "441 "
# define ERR_NOTONCHANNEL "442 "
# define ERR_NOTREGISTERED "451 :You have not registered"
# define ERR_BANNEDFROMCHAN "474 "
# define ERR_CHANOPRIVSNEEDED "482 "
# define ERR_RESTRICTED "484 :Nickname is already in use"
# define ERR_NEEDMOREPARAMS "461 :Not enough parameters"
# define ERR_ALREADYREGISTRED "462 :Unauthorized command (already registered)"
# define ERR_PASSWDMISMATCH "464 :Password incorrect" 
# define ERR_NOPRIVILEGES "481 :Permission Denied- You're not an IRC operator"
# define ERR_UMODEUNKNOWNFLAG "501 :Unknown MODE flag"
# define ERR_USERSDONTMATCH "502 :Cannot change mode for other users"

#endif
